name: GitHub CI
on: [push]

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows64_build:
    name: Windows x86_64 Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel libtool autogen automake autoconf git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-libevent mingw-w64-x86_64-pcre mingw-w64-x86_64-zstd mingw-w64-x86_64-pcre2 mingw-w64-x86_64-freetype mingw-w64-x86_64-libpng mingw-w64-x86_64-bzip2 mingw-w64-x86_64-openssl mingw-w64-x86_64-libsodium mingw-w64-x86_64-c-ares mingw-w64-x86_64-boost mingw-w64-x86_64-libmariadbclient unzip p7zip
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Cache built dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-maindeps-64
      with:
        path: ~/maindeps
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/FETCH_HEAD') }} # key from git repos
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache built clients
      uses: actions/cache@v4
      env:
        cache-name: cache-clients-64
      with:
        path: ~/clients
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/FETCH_HEAD') }} # key from git repos
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
# ----------------------------------------------------------------
# 必须插入下面这个步骤，用于强制修改构建脚本，把 zstd 和 curl 加进去
# ----------------------------------------------------------------
    - name: Patch client build script for Trojan dependencies
      run: |
        sed -i 's|cmake -DMYSQL_INCLUDE_DIR|sed -i "s/mysqlclient/mysqlclient zstd curl crypt32/g" CMakeLists.txt \&\& cmake -DMYSQL_INCLUDE_DIR|' scripts/build.windows.clients.sh
    - name: Build dependencies and clients
      run: |
        bash scripts/build.windows.maindeps.sh
        bash scripts/build.windows.clients.sh
    - name: Build main program
      run: |
        bash scripts/build.windows.release.sh
        mv $USERPROFILE/clients/built/websocketd.exe base/tools/gui/
        mv $USERPROFILE/clients/built base/tools/clients
        mv base stairspeedtest
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: stairspeedtest_reborn_win64
        path: stairspeedtest/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: tar czf stairspeedtest_reborn_win64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stairspeedtest_reborn_win64.tar.gz
        draft: true
